name: go-licenses

on:
  push:
    branches: ["main-tempoff"]

permissions:
  contents: read

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
      - name: Get google/go-licenses package
        run: cd ${{ github.workspace }}; go install github.com/google/go-licenses/v2@latest
      - name: go-licenses
        run: cd ${{ github.workspace }}; go-licenses check --allowed_licenses=Apache-2.0,BSD-3-Clause,BSD-2-Clause,MIT
